<a href="https://colab.research.google.com/github/rsantos182003/pytorch-deep-learning/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.4.0+cu121


In [2]:
print('hello')

hello


In [ ]:
!nvidia-smi

Sat Aug 31 20:29:30 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
scalar =  torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## Random Tensor

In [20]:
# create random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3468, 0.3014, 0.0141, 0.9755],
        [0.8875, 0.9094, 0.8621, 0.5329],
        [0.1631, 0.5162, 0.5709, 0.4660]])

In [4]:
random_tensor.ndim

2

In [5]:
random_tensor2 = torch.rand(1,10,10)
random_tensor2

tensor([[[0.7794, 0.5581, 0.4533, 0.2908, 0.6579, 0.5933, 0.6864, 0.1130,
          0.1829, 0.9382],
         [0.9997, 0.9396, 0.6592, 0.4590, 0.6058, 0.0048, 0.3738, 0.6289,
          0.7273, 0.9971],
         [0.5647, 0.4137, 0.9232, 0.3013, 0.9699, 0.6115, 0.8676, 0.3719,
          0.8844, 0.4307],
         [0.4750, 0.6369, 0.0470, 0.1549, 0.7263, 0.5837, 0.0304, 0.1048,
          0.0256, 0.7907],
         [0.0852, 0.7503, 0.8873, 0.0212, 0.4158, 0.9115, 0.6654, 0.3532,
          0.5151, 0.8730],
         [0.2282, 0.2953, 0.7643, 0.2921, 0.1389, 0.3108, 0.8913, 0.5559,
          0.5880, 0.4612],
         [0.5705, 0.9902, 0.9700, 0.1213, 0.6140, 0.4938, 0.9642, 0.3125,
          0.0872, 0.9457],
         [0.1410, 0.8095, 0.0875, 0.4998, 0.3236, 0.8855, 0.2074, 0.4940,
          0.8848, 0.7930],
         [0.5034, 0.0545, 0.2635, 0.7141, 0.8771, 0.7893, 0.3049, 0.3199,
          0.8606, 0.8722],
         [0.6568, 0.7891, 0.1630, 0.5789, 0.0117, 0.1324, 0.8834, 0.5025,
          0.0835,

In [8]:
random_tensor2.ndim
random_tensor2.size()

torch.Size([1, 10, 10])

In [9]:
random_tensor3 = torch.rand(10,10,10)
random_tensor3

tensor([[[0.6264, 0.8918, 0.1967, 0.6453, 0.7881, 0.0303, 0.2872, 0.3836,
          0.6461, 0.3894],
         [0.8309, 0.4904, 0.5984, 0.2328, 0.8934, 0.6587, 0.0238, 0.1471,
          0.6128, 0.3029],
         [0.4258, 0.5355, 0.6740, 0.7805, 0.1599, 0.1796, 0.6395, 0.9122,
          0.7570, 0.1265],
         [0.8923, 0.8821, 0.1140, 0.4628, 0.4576, 0.2057, 0.6897, 0.7973,
          0.6017, 0.9278],
         [0.0934, 0.4769, 0.4541, 0.1885, 0.2914, 0.8004, 0.6028, 0.2452,
          0.7953, 0.1072],
         [0.9053, 0.4990, 0.2566, 0.3250, 0.6925, 0.3169, 0.5917, 0.0916,
          0.3922, 0.7455],
         [0.0928, 0.0311, 0.5637, 0.9971, 0.4305, 0.3249, 0.1980, 0.2298,
          0.6667, 0.5677],
         [0.6147, 0.3300, 0.8840, 0.4227, 0.9825, 0.5439, 0.1459, 0.9417,
          0.7185, 0.5532],
         [0.0233, 0.5345, 0.1630, 0.3842, 0.1175, 0.3371, 0.3120, 0.9639,
          0.9578, 0.3725],
         [0.3345, 0.4456, 0.8679, 0.8785, 0.5170, 0.8914, 0.5548, 0.5628,
          0.1943,

In [18]:
#create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(3, 224,224) # colour channel, width, height
random_image_size_tensor


tensor([[[0.2471, 0.8323, 0.1283,  ..., 0.7909, 0.8781, 0.1836],
         [0.9076, 0.6640, 0.9668,  ..., 0.4867, 0.1326, 0.1510],
         [0.2725, 0.4677, 0.3313,  ..., 0.9039, 0.5029, 0.3801],
         ...,
         [0.0942, 0.8844, 0.8977,  ..., 0.7421, 0.3812, 0.9975],
         [0.8223, 0.4356, 0.1074,  ..., 0.5075, 0.5292, 0.3242],
         [0.3796, 0.4994, 0.8566,  ..., 0.2475, 0.8003, 0.8531]],

        [[0.9583, 0.8866, 0.5550,  ..., 0.8608, 0.5294, 0.4590],
         [0.7654, 0.5045, 0.5279,  ..., 0.1105, 0.2884, 0.4615],
         [0.7372, 0.0805, 0.8961,  ..., 0.4195, 0.5987, 0.0480],
         ...,
         [0.7980, 0.1629, 0.7242,  ..., 0.1407, 0.6374, 0.3596],
         [0.2242, 0.8448, 0.0499,  ..., 0.4092, 0.2550, 0.1253],
         [0.7891, 0.3097, 0.4399,  ..., 0.8471, 0.4296, 0.7619]],

        [[0.9889, 0.5511, 0.0400,  ..., 0.6370, 0.2500, 0.6488],
         [0.4833, 0.7288, 0.8704,  ..., 0.8258, 0.3854, 0.5183],
         [0.7095, 0.7888, 0.9072,  ..., 0.0854, 0.0653, 0.

In [19]:
random_image_size_tensor.size(),random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [23]:
# create tensor of all zeros
zeros = torch.zeros(size=(3,4)) #zeros is usually used as masked
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# create tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones*random_tensor

tensor([[0.3468, 0.3014, 0.0141, 0.9755],
        [0.8875, 0.9094, 0.8621, 0.5329],
        [0.1631, 0.5162, 0.5709, 0.4660]])

In [27]:
ones.dtype # dtype -> means default data type, torch.float32

torch.float32

## Creating a range of tensors or tensor-like

In [28]:
torch.range(0,10) # deprecated, will be remove in the future

<ipython-input-28-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
# torch.arange(0,10)
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
torch.__version__

'2.4.0+cu121'

In [34]:
torch.arange(start=0,end=1000,step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [35]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1.) Tensors not right datatype
2.) Tensors not right shape
3.) Tensors not on the right device

In [36]:
#float32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [46]:
float_32_tensor.dtype

torch.float32

In [38]:
#float16 tensor
float_16_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_16_tensor
float_16_tensor.dtype

torch.float16

In [47]:
float_16_tensor.dtype

torch.float16

In [43]:
#float tensor
float_tensor = torch.tensor([3.0,6.0,9.0], dtype=None,
                            device=None, #what device is your tensor on # by default device='cpu'; can also be set as device='cuda'
                            requires_grad=False # wether or not to track gradients with this tensor operations
                            )
float_tensor
float_tensor.dtype

torch.float32

In [44]:
float_16_tensor2 = float_32_tensor.type(torch.float16)
float_16_tensor2

tensor([3., 6., 9.], dtype=torch.float16)

In [48]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [52]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [53]:
int_32_tensor.dtype

torch.int32

In [54]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to do get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to do get device from a tensor, can use `tensor.device`

In [55]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9830, 0.4508, 0.4274, 0.9872],
        [0.1869, 0.1934, 0.1364, 0.7612],
        [0.2138, 0.0363, 0.9248, 0.3552]])

In [56]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9830, 0.4508, 0.4274, 0.9872],
        [0.1869, 0.1934, 0.1364, 0.7612],
        [0.2138, 0.0363, 0.9248, 0.3552]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [59]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [60]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [61]:
# Subract 10
tensor - 10

tensor([-9, -8, -7])

In [62]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [63]:
torch.add(tensor,10)

tensor([11, 12, 13])